### ISSUE TITLE
CLPC stands for Closed Loop Performance Controller

### ISSUE THREAD

**Issue by junjie1475** [Androp0v/PowerMetricsKit#1]
Very nice project! Just some side notes, CLPC reads the DPE(Digital power estimator) register to get energy information, and it works on A14 too.

**Comment by Androp0v** [comment]
> Very nice project! Just some side notes, CLPC reads the DPE(Digital power estimator) register to get energy information, and it works on A14 too.

Thanks! I'll update the project to fix the definition of CLPC when I get a chance. Didn't know about the DPE or how `proc_pidinfo` retrieved this information internally, this has mostly been the result of disassembling `powermetrics`, so thank you for pointing me in that direction as well, I'll see if I can find a reliable source to reference and add that to the documentation too. It's hard to get high quality information on this kind of low-level details of Apple platforms tbh 😅

**Comment by junjie1475** [comment]
> well, I'll see if I can find a reliable source to reference and add that to the documentation too. It's hard to get high quality information on this kind of low-level details of Apple platforms tbh 😅

You can search DPE on Apple’s XNU
Repo or if you have time, just search CLPC in Google patent which will bring you to related patents.

**Comment by Androp0v** [comment]
Updated the repo to fix the meaning of CLPC + adding a mention of the DPE. Thanks again for pointing me in the right direction! 🙇‍♂️ I'll keep expanding the documentation of the project if I can.
